[package]
name = "oxfmt"
version = "0.4.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
downcast-rs = "2.0.1"
oxfmt_derive = { path = "../oxfmt_derive" }

[lib]
name = "oxfmt"
path = "src/lib.rs"
