name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build root project
      run: cargo build --verbose

    - name: Run tests for root project
      run: cargo test --verbose

    - name: Build mcmodbuild
      working-directory: mcmodbuild
      run: cargo build --verbose

    - name: Run tests for mcmodbuild
      working-directory: mcmodbuild
      run: cargo test --verbose

    - name: Build oxfmt
      working-directory: oxfmt
      run: cargo build --verbose

    - name: Run tests for oxfmt
      working-directory: oxfmt
      run: cargo test --verbose
